"use strict";
console.log('Ahmed');
console.log("jaan");
var myname = 'faisal';
console.log(myname);
var message = "I have started learning typescript";
console.log(message);
var num1 = 2;
console.log(num1);
var num2 = 3;
var num3 = 4;
var num4 = 5;
var num5 = 6;
var num6 = 7;
var num7 = 8;
var num8 = 9;
var num9 = 10;
var num10 = 10;
var adding = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log(adding);
var subtracting = num1 - num2;
console.log(subtracting);
var multiplying = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log(multiplying);
var dividing = num1 / num2;
console.log(dividing);
var myNameIs = 'faisal';
console.log(myNameIs);
