console.log('Ahmed');
var myname:string='faisal';
console.log(myname);
var message:string="I have started learning typescript";
console.log(message);
var num1:number=2;
console.log(num1);
var num2:number=3;
var num3:number=4;
var num4:number=5;
var num5:number=6;
var num6:number=7;
var num7:number=8;
var num8:number=9;
var num9:number=10;
var num10:number=10;
var adding:number=num1+num2+num3+num4+num5+num6+num7+num8+num9+num10;
console.log(adding);
var subtracting:number=num1-num2;
console.log(subtracting);
var multiplying:number=num1*num2*num3*num4*num5*num6*num7*num8*num9*num10;
console.log(multiplying);
var dividing:number=num1/num2;
console.log(dividing);
var myNameIs:string='faisal';
console.log(myNameIs);
